{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "import a2i\n",
    "from tkinter import filedialog\n",
    "from tkinter.ttk import *\n",
    "from PIL import Image\n",
    "\n",
    "def convert_image(input_path, output_path, image_format):\n",
    "    try:\n",
    "        if image_format == \"Grayscale\":\n",
    "            a2i.convert_apk_to_img(input_path,output_path)\n",
    "        else:\n",
    "            pass\n",
    "        result_label.config(text=\"Chuyển đổi thành công!\", fg=\"green\")\n",
    "    except Exception as e:\n",
    "        result_label.config(text=f\"Lỗi: {e}\", fg=\"red\")\n",
    "\n",
    "def browse_file():\n",
    "    file_path = filedialog.askopenfilename(title=\"Chọn file\", filetypes=[(\"APK files\", \"*.apk\")])\n",
    "    input_entry.delete(0, tk.END)\n",
    "    input_entry.insert(0, file_path)\n",
    "\n",
    "def save_file():\n",
    "    input_path = input_entry.get()\n",
    "    image_format = select_type_img.get()\n",
    "    output_path = filedialog.asksaveasfilename(title=\"Chọn nơi lưu\", defaultextension=\".png\", filetypes=[(\"PNG files\", \"*.png\")])\n",
    "    if input_path and output_path:\n",
    "        convert_image(input_path, output_path, image_format)\n",
    "\n",
    "\n",
    "# Tạo cửa sổ chính\n",
    "root = tk.Tk()\n",
    "root.title(\"Chuyển đổi ảnh PNG\")\n",
    "\n",
    "# Tạo và định vị các widget\n",
    "input_label = tk.Label(root, text=\"Chọn tập tin apk:\")\n",
    "input_label.grid(row=0, column=0, padx=10, pady=10)\n",
    "\n",
    "input_entry = tk.Entry(root, width=60)\n",
    "input_entry.grid(row=0, column=1, padx=100, pady=10)\n",
    "\n",
    "browse_button = tk.Button(root, text=\"Chọn\", command=browse_file)\n",
    "browse_button.grid(row=0, column=2, padx=10, pady=10)\n",
    "\n",
    "select_type_img = Combobox(root, font = ('Arial',10),width = 20)\n",
    "select_type_img['value'] = ('Grayscale','RGB')\n",
    "select_type_img.grid(row=1, column=1, padx=10, pady=10)\n",
    "select_type_img.current(0)\n",
    "type = select_type_img.get()\n",
    "\n",
    "convert_button = tk.Button(root, text=\"Chuyển đổi\", command=save_file)\n",
    "convert_button.grid(row=1, column=2, pady=10)\n",
    "\n",
    "result_label = tk.Label(root, text=\"\", fg=\"black\")\n",
    "result_label.grid(row=2, column=0, columnspan=3, pady=10)\n",
    "\n",
    "# Bắt đầu vòng lặp sự kiện\n",
    "root.mainloop()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
